#!/usr/bin/env python3.7

## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License Version 2 as published by
## the Free Software Foundation.
#
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License at (http://www.gnu.org/licenses/) for
## more details.


"""
Private Internet Access front-end for openvpn.

Based on original pia.sh Bash script from https://github.com/d4rkcat/pia.

It is only tested on Linux, but is intended to be portable to other systems.

Porting to Windows will likely require some work, but assumptions about the
target system were avoided or at least made clear.
"""

import sys
import os
if sys.version_info.major < 3:
    sys.stderr.write('ERROR: This script requires Python version 3.{}'.format(os.linesep))
    sys.exit(1)

from lib import command


if __name__ == '__main__':
    try:
        command.main('OpenVPN front-end for Private Internet Access')
    except KeyboardInterrupt:
        sys.exit(2)
